### PR TITLE
Allow multiple drupal

### PR DESCRIPTION
**Pull request by whikloj**

### CODE REVIEW

**Comment by whikloj** [comment]
@Islandora/8-x-committers this should have no effect on current builds but will enable multiple Drupal version testing ala https://github.com/Islandora/islandora/pull/821

**Review by elizoller — APPROVED** [review]
looks like https://github.com/Islandora/islandora/pull/821 tests went green for 8.9 and 9.1 so we should be good to go, right?

**Comment by whikloj** [comment]
No, https://github.com/Islandora/islandora/pull/821 passed because islandora_ci can only run 8.9.11. It just ran it 6 times instead of 3.

**Comment by whikloj** [comment]
Before I opened the draft pr 8 did run a test. I can show you how to run your own tomorrow if you'd like.

**Comment by elizoller** [comment]
Ah ok, talk to you tomorrow then 👍

**Comment by elizoller** [comment]
With @whikloj 's help, i was able to test the islandora_ci change on the islandora module here: https://travis-ci.com/github/asulibraries/islandora/builds/212494945
which created 12 builds
php 7.3 / drupal 8 / kernel
php 7.3 / drupal 8 / functional
php 7.3 / drupal 8 / functional-javascript
php 7.3 / drupal 9 / kernel
php 7.3 / drupal 9 / functional
php 7.3 / drupal 9 / functional-javascript
php 7.4 / drupal 8 / kernel
php 7.4 / drupal 8 / functional
php 7.4 / drupal 8 / functional-javascript
php 7.4 / drupal 9 / kernel
php 7.4 / drupal 9 / functional
php 7.4 / drupal 9 / functional-javascript

verified that the correct PHP version and drupal version was installed so i think this is good to go

**Pull request merged**
